.github/CODEOWNERS
source/electrical_heating/electrical_heating_job/entry_point.py
source/electrical_heating/setup.py

Added electrical heating wheel. 
Added Mandaloiren som CODEOWNER.

feat: Added electrical heating wheel 

---

source/electrical_heating/electrical_heating_job/entry_points/job_args/electrical_heating_args.py

test: New commet

---

.docker/Dockerfile
.docker/entrypoint.sh
.docker/requirements.txt
.docker/spark-defaults.conf
.github/workflows/cd.yml
.github/workflows/ci-electrical-heating.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/detect-changes.yml

Added docker to measurements/electrical heating

feat: Added docker to measurements/electrical heating

---

.docker/Dockerfile
.github/workflows/cd.yml

fix Docker CD

---

source/electrical_heating/contracts/measurements__electrical_heating/time_series_points_v1.py

feat: Add consumption to time series points contract

---

source/electrical_heating/contracts/job-parameters.txt

feat: Add contract for electrical heating job parameters

---

source/electrical_heating/contracts/electricity_market__electrical_heating/child_metering_point_periods_v1.py
source/electrical_heating/contracts/electricity_market__electrical_heating/consumption_metering_point_periods_v1.py
source/electrical_heating/tests/integration_tests/calculation_scenarios/given_a_smoke_test_scenario/when/electricity_market__electrical_heating/child_metering_point_periods_v1.csv

feat: Improve EH metering point contracts

---

source/electrical_heating/electrical_heating/domain/calculation.py
source/electrical_heating/electrical_heating/domain/pyspark_functions.py
source/electrical_heating/electrical_heating/entry_points/entry_point.py
source/electrical_heating/electrical_heating/entry_points/job_args/electrical_heating_args.py
source/electrical_heating/electrical_heating/entry_points/job_args/electrical_heating_job_args.py
source/electrical_heating/electrical_heating/entry_points/job_args/environment_variables.py
source/electrical_heating/electrical_heating/infrastructure/electricity_market/__init__.py
source/electrical_heating/electrical_heating/infrastructure/electricity_market/column_names.py
source/electrical_heating/electrical_heating/infrastructure/electricity_market/database_definitions.py
source/electrical_heating/electrical_heating/infrastructure/electricity_market/repository.py
source/electrical_heating/electrical_heating/infrastructure/measurements_gold/__init__.py
source/electrical_heating/electrical_heating/infrastructure/spark_initializor.py
source/electrical_heating/tests/entry_points/job_args/test_electrical_heating_job_args.py

feat: Add context for EH logic

---

source/electrical_heating/src/electrical_heating/domain/calculation.py
source/electrical_heating/src/electrical_heating/domain/constants.py

feat: Respect electrical heating limit of 4000 kWh

---

.docker/Dockerfile
.docker/requirements.txt
.github/workflows/ci-capacity-settlement.yml
.github/workflows/ci-electrical-heating.yml
.vscode/settings.json
source/.gitignore
source/electrical_heating/src/setup.py
source/electrical_heating/tests/conftest.py
source/electrical_heating/tests/scenario_tests/conftest.py
source/electrical_heating/tests/scenario_tests/given_a_smoke_test_scenario/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_different_periods_hit_different_limits/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_hit_4k_limit/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_move_consumption_to_child_base/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_move_consumption_to_child_filtering_mp/test_scenario.py
source/electrical_heating/tests/scenario_tests/wip_summertime_change/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_wintertime_change/test_scenario.py.disabled
source/electrical_heating/tests/testsession.local.settings.sample.yml
source/electrical_heating/tests/testsession_configuration.py

feat: Enable testsession settings for scenario tests

---

source/electrical_heating/tests/scenario_tests/given_a_smoke_test_scenario/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_different_periods_hit_different_limits/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_hit_4k_limit/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_move_consumption_to_child_base/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_move_consumption_to_child_filtering_mp/test_scenario.py
source/electrical_heating/tests/scenario_tests/wip_summertime_change/test_scenario.py.disabled
source/electrical_heating/tests/scenario_tests/wip_wintertime_change/test_scenario.py.disabled

refac: Simple test rename

---

.github/workflows/cd.yml
.github/workflows/detect-changes.yml

I forgot to add a dispatch deployment for the core workspace.
As I understood, we should put the medallion architecture into the Core workspace. So I am adding the Bronze layer to the Core workspace now. Silver and Gold will be added later on.

feat: Add Core CD

---

source/bronze/pyproject.toml

fix: Update pyproject.toml

---

.github/workflows/detect-changes.yml

Was a bit too fast in the earlier PR. 
`core` in detect_changes was not in output.

fix: CD Core detect_changes

---

source/bronze/pyproject.toml

fix: Update pyproject.toml dependency

---

.github/workflows/ci-orchestrator.yml
source/bronze/src/bronze/infrastructure/schemas/bronze_measurements.py
source/bronze/tests/application/test_migrations.py

Small change to the CI to include `ci_bronze` and `ci_silver` to allow merge, and a small renaming.

Refac: Small change to CI to include packages, and small refac

---

source/capacity_settlement/src/contracts/measurements_bronze/measurements_bronze_v1.py
source/electrical_heating/src/electrical_heating/infrastructure/measurements_bronze/database_definitions.py
source/electrical_heating/src/electrical_heating/infrastructure/measurements_bronze/schemas/measurements_bronze_v1.py

refac(EH/CS): Update bronze schema

---

.devcontainer/bronze/devcontainer.json
.devcontainer/capacity_settlement/devcontainer.json
.devcontainer/electrical_heating/devcontainer.json
.devcontainer/gold/devcontainer.json
.devcontainer/silver/devcontainer.json
templates/devcontainer.json.j2

fix: uv_cache should be set

---

.devcontainer/bronze/devcontainer.json
.devcontainer/capacity_settlement/devcontainer.json
.devcontainer/electrical_heating/devcontainer.json
.devcontainer/gold/devcontainer.json
.devcontainer/silver/devcontainer.json
templates/devcontainer.json.j2

chore: auto save and format files when changing focus in the ide

---

source/bronze/pyproject.toml
source/bronze/uv.lock
source/capacity_settlement/pyproject.toml
source/capacity_settlement/uv.lock
source/electrical_heating/pyproject.toml
source/electrical_heating/tests/electrical_heating_tests/application/job_args/test_electrical_heating_job_args.py
source/electrical_heating/uv.lock
source/gold/pyproject.toml
source/gold/uv.lock
source/silver/pyproject.toml
source/silver/uv.lock

Added the flag (-s) so that print() always writes to output.
Volt has approved this flag.

test: Added flag so that print writes to output

---

.gitignore

chore: Ignore generated folder `spark-warehouse`

---

.github/workflows/cd.yml
.github/workflows/reusable-cd.yml

ci: maybe github_token cannot be passed as an input?

---

.github/workflows/cd.yml
.github/workflows/reusable-cd.yml

ci: secret name within can not be used since it would collide with system reserved name

---

.github/workflows/reusable-cd.yml

ci: cd should not fail if there are no releases

---

.github/workflows/reusable-cd.yml

ci: powershell does not like

---

source/capacity_settlement/src/opengeh_capacity_settlement/domain/calculation.py
source/capacity_settlement/tests/scenario_tests/given_a_smoke_test_scenario_with_decimal/test_scenario.py

refac: quantity decimal scale 3

---

source/electrical_heating/src/opengeh_electrical_heating/infrastructure/electricity_market/schemas/consumption_metering_point_periods_v1.py

fix(EH): Set settlement method nullable=False

---

source/bronze/src/opengeh_bronze/application/settings/__init__.py
source/bronze/src/opengeh_bronze/application/settings/kafka_authentication_settings.py
source/bronze/src/opengeh_bronze/application/settings/submitted_transactions_stream_settings.py
source/bronze/src/opengeh_bronze/application/streams/submitted_transactions.py
source/bronze/src/opengeh_bronze/domain/constants/column_names/bronze_measurements_column_names.py
source/bronze/src/opengeh_bronze/infrastructure/streams/kafka_stream.py
source/bronze/tests/application/settings/test_kafka_authentication_settings.py
source/bronze/tests/application/settings/test_submitted_transactions_stream_settings.py

Enable continuous streaming of eventhub data

---

source/electrical_heating/src/opengeh_electrical_heating/application/__init__.py
source/electrical_heating/src/opengeh_electrical_heating/application/calculation.py
source/electrical_heating/src/opengeh_electrical_heating/application/job_args/electrical_heating_job_args.py
source/electrical_heating/src/opengeh_electrical_heating/domain/__init__.py
source/electrical_heating/src/opengeh_electrical_heating/domain/calculation.py
source/electrical_heating/src/opengeh_electrical_heating/domain/calculation_results.py
source/electrical_heating/src/opengeh_electrical_heating/entry_point.py
source/electrical_heating/tests/job_tests/test_electrical_heating_job.py
source/electrical_heating/tests/scenario_tests/conftest.py

Now circular dependencies between these parts have been removed and domain no longer depends on other parts.
N/A

refac(EH): Remove domain to infra dependency

---

.devcontainer/bronze/devcontainer.json
.devcontainer/capacity_settlement/devcontainer.json
.devcontainer/electrical_heating/devcontainer.json
.devcontainer/gold/devcontainer.json
.devcontainer/silver/devcontainer.json

project: enable basic type checking for pylance

---

source/electrical_heating/tests/.sample.env
source/electrical_heating/tests/container_tests/conftest.py
source/electrical_heating/tests/container_tests/environment_configuration.py
source/electrical_heating/tests/container_tests/requirements.txt
source/electrical_heating/tests/container_tests/test_container.py

Added environment variables to container test (electrical heating).
Uses Pydantic settings.

feat: Added environment variables to container tests

---

source/capacity_settlement/tests/conftest.py
source/electrical_heating/tests/conftest.py

refac: Skip container test locally if .env file does not exist

---

source/core/src/core/bronze/domain/constants/__init__.py
source/core/src/core/bronze/domain/constants/database_names.py
source/core/src/core/bronze/infrastructure/streams/bronze_repository.py
source/core/src/core/bronze/infrastructure/streams/kafka_stream.py
source/core/src/core/gold/infrastructure/adapters/delta_silver_adapter.py
source/core/src/core/gold/infrastructure/config/__init__.py
source/core/src/core/migrations/migrations_runner.py
source/core/src/core/migrations/substitutions.py
source/core/src/core/settings/catalog_settings.py
source/core/src/core/silver/application/streams/calculated_stream.py
source/core/src/core/silver/infrastructure/config/__init__.py
source/core/src/core/silver/infrastructure/config/database_names.py
source/core/src/core/silver/infrastructure/helpers/environment_variable_helper.py
source/core/src/core/silver/infrastructure/streams/bronze_repository.py
source/core/tests/bronze/conftest.py
source/core/tests/gold/conftest.py
source/core/tests/gold/infrastructure/adapters/test_delta_gold_adapter.py
source/core/tests/gold/infrastructure/adapters/test_delta_silver_adapter.py
source/core/tests/migrations/conftest.py
source/core/tests/migrations/test_migrations.py
source/core/tests/settings/conftest.py
source/core/tests/settings/test_catalog_settings.py
source/core/tests/silver/application/streams/test_stream.py
source/core/tests/silver/conftest.py

Add catalog settings env vars

---

.github/PULL_REQUEST_TEMPLATE.md

chore: We're not open-source

---

source/core/src/core/gold/infrastructure/adapters/delta_gold_adapter.py
source/core/src/core/gold/infrastructure/adapters/delta_silver_adapter.py
source/core/src/core/utility/shared_helpers.py
source/core/tests/utility/test_shared_helpers.py

Refactoring, initiated by [this comment](https://github.com/Energinet-DataHub/opengeh-measurements/pull/243#discussion_r1948505213) on [PR 243](https://github.com/Energinet-DataHub/opengeh-measurements/pull/243)

refac: Remove get_full_table_name function

---

source/geh_calculated_measurements/tests/.sample.env
source/geh_calculated_measurements/tests/capacity_settlement/.sample.env
source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/environment_configuration.py
source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/test_container.py
source/geh_calculated_measurements/tests/electrical_heating/.sample.env
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/environment_configuration.py
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/test_container.py

refac: fix subsystem test local

---

source/geh_calculated_measurements/tests/capacity_settlement/conftest.py
source/geh_calculated_measurements/tests/conftest.py
source/geh_calculated_measurements/tests/electrical_heating/conftest.py

refac: Local skip subsystem test if no .env file

---

.devcontainer/calculated_measurements/devcontainer.json

https://github.com/astral-sh/ruff/discussions/15991

refac: Remove deprecated ruff setting

---

.devcontainer/calculated/devcontainer.json
.docker/Dockerfile

fix: typo in devcontainer

---

.vscode/settings.json
source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/application/execute_with_deps.py
source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/fixtures/capacity_settlement_fixture.py
source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/test_capacity_settlement.py
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/fixtures/eletrical_heating_fixture.py
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/test_electrical_heating.py

Enabled test logging to Log Analytics.
Renamed a setting and added a dummy function to fire the execution of the job.

test: Enabled capacity settlement subsystem test (no. 4)

---

.github/workflows/cd.yml

Fix event type for repo dispatch

---

source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/application/capacity_settlement_args.py
source/geh_calculated_measurements/tests/capacity_settlement/capacity_settlement_tests/application/job_args/test_capacity_settlement_job_args.py
source/geh_calculated_measurements/tests/capacity_settlement/scenario_tests/conftest.py

fix: Subsystem test

---

source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/conftest.py
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/environment_configuration.py

fix: Use applicationsettings

---

.devcontainer/calculated/devcontainer.json

chore: add gitlens extension to calculated devcontainer

---

source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/application/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/infrastructure/electricity_market/schema.py

refac: Calculated measurements

---

source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/test_capacity_settlement.py
source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/test_electrical_heating.py

Renamed the function to align with Wholesale subsystem test.
Wait for PR https://github.com/Energinet-DataHub/opengeh-measurements/pull/352

test: Enabled capacity settlement subsystem test (step 4)

---

source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/application/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/domain/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/domain/calculation_output.py
source/geh_calculated_measurements/src/geh_calculated_measurements/common/infrastructure/calculated_measurements/database_definitions.py
source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/migration_scripts/20250305100000_drop_measurements_table.sql
source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/migration_scripts/20250305100100_create_calculated_measurements.sql
source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/settings/catalog_settings.py
source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/substitutions.py
source/geh_calculated_measurements/tests/capacity_settlement/scenario_tests/conftest.py

https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13675032562/job/38233651617

refac: Calculation measurements migration

---

source/geh_calculated_measurements/README.md

chore: provoke change to test cd

---

source/core/tests/migrations/test_views.py

Fix flaky test in test_views

---

docs/core/merge_strategy.md

- https://github.com/Energinet-DataHub/team-volt/issues/1009

docs: Update merge_strategy

---

source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/infrastructure/measurements_gold/repository.py

fix: Use correct name MEASUREMENTS

---

source/geh_calculated_measurements/tests/conftest.py

refac: Remove skip subsystem test 

---

source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/entry_point.py
source/geh_calculated_measurements/src/geh_calculated_measurements/capacity_settlement/infrastructure/measurements_gold/schema.py
source/geh_calculated_measurements/src/geh_calculated_measurements/common/infrastructure/calculated_measurements/database_definitions.py
source/geh_calculated_measurements/tests/capacity_settlement/conftest.py
source/geh_calculated_measurements/tests/capacity_settlement/job_tests/conftest.py
source/geh_calculated_measurements/tests/capacity_settlement/job_tests/test_capacity_settlement_job.py
source/geh_calculated_measurements/tests/capacity_settlement/job_tests/test_files/measurements_gold-capacity_settlement_v1.csv
source/geh_calculated_measurements/tests/capacity_settlement/job_tests/test_files/metering_point_periods_v1.csv
source/geh_calculated_measurements/tests/capacity_settlement/scenario_tests/conftest.py

test: Enable capacity settlement job test

---

source/core/src/core/gold/entry_points.py
source/core/tests/gold/test_entry_points.py

Fix entrypoint in gold layer

---

source/geh_calculated_measurements/tests/capacity_settlement/scenario_tests/conftest.py
source/geh_calculated_measurements/tests/electrical_heating/scenario_tests/conftest.py

This PR appears to bring down test time of geh_calculated_measurements from >5min to ~3.5min.
Even though it only affects scenario tests in electrical heating.

feat(EH): Optimize scenario tests performance

---

source/core/pyproject.toml
source/geh_calculated_measurements/pyproject.toml

chore: upgrade geh_common to latest

---

.editorconfig

chore: Json indent=2

---

source/geh_calculated_measurements/src/geh_calculated_measurements/testing/utilities/dataframes.py

refac: Don't log data frames in CI

---

source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/__init__.py
source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/ephemeral_column_names.py
source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/transformations/common.py
source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/transformations/electrical_heating_calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/electrical_heating/domain/transformations/metering_points.py
source/geh_calculated_measurements/tests/electrical_heating/electrical_heating_tests/infrastructure/test_column_names.py

refac: Fix typo in "ephemeral"

---

source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj

Update abstractions docs

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj

Bump nuget version

---

source/geh_calculated_measurements/tests/.sample.env
source/geh_calculated_measurements/tests/subsystem_tests/capacity_settlement/environment_configuration.py
source/geh_calculated_measurements/tests/subsystem_tests/electrical_heating/environment_configuration.py

https://github.com/Energinet-DataHub/dh3-environments/pull/1394

refac: Use calculated measurements warehouse id

---

source/dotnet/Measurements.Application/Persistence/MeasurementsResult.cs
source/dotnet/Measurements.Application/Responses/GetMeasurementResponse.cs
source/dotnet/Measurements.Domain/Quality.cs
source/dotnet/Measurements.Domain/Unit.cs
source/dotnet/Measurements.Infrastructure/Persistence/MeasurementsGoldConstants.cs
source/dotnet/Measurements.Infrastructure/Persistence/Queries/GetMeasurementsQuery.cs
source/dotnet/Measurements.UnitTests/Handlers/MeasurementsHandlerTests.cs
source/dotnet/Measurements.UnitTests/Responses/GetMeasurementResponseTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Controllers/MeasurementsControllerTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Fixtures/WebApiFixture.cs

Expand unit and quality

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/IMeasurementsClient.cs
source/dotnet/Measurements.Client/Measurements.Client.csproj

MeasurementsClient bump to version 1.1.0

---

source/core/src/core/silver/infrastructure/repositories/submitted_transactions_repository.py
source/core/tests/helpers/builders/submitted_transactions_builder.py

fix: Notify ProcessManager

---

source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/infrastucture/electrical_market/schema.py

This reverts commit e6b63ab2d7696e335841cd7fa28b54f349749d8a.

Revert "fix subsystem test (#433)"

---

source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/application/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/entry_point.py

refac: Update entry_point.py net consumption group 6

---

source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/daily.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/model/__init__.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/model/child_metering_points.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/model/consumption_metering_point_periods.py
source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/model/time_series_points.py

Introduce new data models to improve the calculation functions for consumption and time series points. Update the execution logic to utilize these models, enhancing data handling and processing capabilities.

Enhance calculation functions with new data models for consumption and time series points

---

.devcontainer/calculated/devcontainer.json

refac: Add github pull request extention

---

source/dotnet/Measurements.Client.Tests/Fixtures/MeasurementsClientFixture.cs
source/dotnet/Measurements.Client.Tests/MeasurementsClientTests.cs
source/dotnet/Measurements.Infrastructure/Persistence/MeasurementsGoldConstants.cs
source/dotnet/Measurements.Infrastructure/Persistence/Queries/GetMeasurementsQuery.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Controllers/MeasurementsControllerTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Fixtures/WebApiFixture.cs

Measurementsapi filter most recent observations

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj

Bump Client version to 1.4.0

---

docs/core/transformations/migrated_to_measurements_silver_transformation.md

https://github.com/Energinet-DataHub/team-volt/issues/1073

docs: add `unit` mapping for migrations to measurements

---

source/geh_calculated_measurements/tests/capacity_settlement/scenario_tests/conftest.py
source/geh_calculated_measurements/tests/electrical_heating/scenario_tests/conftest.py
source/geh_calculated_measurements/tests/net_consumption_group_6/scenario_tests/conftest.py

fix issue where scenario test fail on missing _TRACER_NAME

refac: Add dummy _logging to test_cases

---

source/core/src/core/silver/infrastructure/repositories/silver_measurements_repository.py
source/core/src/core/silver/infrastructure/repositories/submitted_transactions_repository.py
source/core/tests/silver/infrastructure/repositories/test_submitted_transactions_repository.py

fix `skipChangeCommits` type

---

.github/workflows/ci-orchestrator.yml

ci: you have to wait for integration tests to finish

---

source/core/pyproject.toml
source/core/tests/conftest.py
source/core/uv.lock

- https://github.com/Energinet-DataHub/team-volt/issues/1061

refac: use geh_common spark session and clean up conftest

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj

Bump measurements api version

---

docs/core/table_definitions/gold_measurements.md
source/core/src/core/migrations/migration_scripts/20250404085500_add_orchestration_type_cluster_key_to_gold.sql

- https://github.com/Energinet-DataHub/team-volt/issues/1128

add new cluster key for gold measurements

---

source/geh_calculated_measurements/src/geh_calculated_measurements/missing_measurements_log/domain/calculation.py
source/geh_calculated_measurements/src/geh_calculated_measurements/missing_measurements_log/infrastructure/repository.py
source/geh_calculated_measurements/tests/common/infrastructure/current_measurements/test_repository.py
source/geh_calculated_measurements/tests/missing_measurements_log/job_tests/test_missing_measurements_log_job.py
source/geh_calculated_measurements/tests/missing_measurements_log/missing_measurements_log_tests/infrastructure/test_repository.py

Improve the repository's read method to facilitate mocking in tests and ensure schema validation. Update tests to reflect these changes and enhance their reliability.

Refactor repository read method and enhance schema validation tests

---

source/core/tests/subsystem_tests/step_definitions/test_streaming_of_calculated_measurements.py

fix Subsystem test given

---

source/geh_calculated_measurements/src/geh_calculated_measurements/testing/utilities/job_tester.py
source/geh_calculated_measurements/tests/integration/testing/test_job_test_fixture.py
source/geh_calculated_measurements/tests/subsystem_tests/environment_configuration.py

chore: improves error messaging when log query fails

---

source/core/tests/subsystem_tests/step_definitions/test_streaming_of_calculated_measurements.py

fix: Subsystem test, typo

---

source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj
source/dotnet/Measurements.UnitTests/Domain/Extensions/DateExtensionTests.cs

Bump MeasurementsClient and Abstractions to 2.2.0
https://github.com/Energinet-DataHub/team-volt/issues/1109

Measurementsapi client version bump

---

source/core/pyproject.toml
source/core/tests/integration/migrations/test_views.py

On request from Mandalorian, the contract is explicit telling that the fields in the view are not nullable
changed in python package
https://github.com/Energinet-DataHub/opengeh-python-packages/pull/145

chore: bump python-package version

---

source/core/src/core/gold/infrastructure/repositories/calculated_measurements_repository.py

fix: Set `skipChangeCommits` on calculated stream

---

source/core/tests/conftest.py
source/core/tests/integration/bronze/infrastructure/repositories/test_int_migrated_transaction_repositories.py
source/core/tests/integration/bronze/infrastructure/repositories/test_invalid_submitted_transactions_repository.py
source/core/tests/integration/bronze/infrastructure/repositories/test_submitted_transactions.py
source/core/tests/integration/bronze/infrastructure/repositories/test_submitted_transactions_quarantined_repository.py
source/core/tests/integration/conftest.py
source/core/tests/integration/gold/application/streams/test_calculated_measurements_stream.py
source/core/tests/integration/gold/application/streams/test_gold_measurements_stream.py
source/core/tests/integration/migrations/test_migrations.py
source/core/tests/integration/migrations/test_views.py
source/core/tests/integration/silver/application/streams/test_migrated_transactions.py
source/core/tests/integration/silver/application/streams/test_submitted_transactions.py
source/core/tests/integration/silver/infrastructure/repositories/test_silver_measurements_repository.py

Autouse the migrations_executed. Then it is not needed to use the fixture in all tests.

refac: Migration Executed in integration tests

---

source/core/tests/integration/features/silver.feature
source/core/tests/integration/step_definitions/test_silver.py

refactor: Generalize measurement scenarios in integration tests

---

source/core/tests/integration/features/stream_bronze_to_silver.feature
source/core/tests/integration/step_definitions/test_stream_bronze_to_silver.py

refactor: Update scenario descriptions

---

source/core/src/core/gold/infrastructure/repositories/gold_measurements_repository.py

fix: silver to gold stream

---

source/core/tests/subsystem_tests/features/streaming_of_migrated_measurements.feature
source/core/tests/subsystem_tests/step_definitions/test_streaming_of_migrated_measurements.py

Fixed text in a given / when / then scenario

test: fixed given, when, then

---

source/core/tests/subsystem_tests/features/streaming_of_migrated_measurements.feature

test: changed capitall letter in streaming_of_migrated_measurements.feature 

---

source/geh_calculated_measurements/tests/.sample.env

refac: Update .sample.env

---

source/geh_calculated_measurements/tests/data_products/contract_tests/test_contract_and_data_product_equality.py

The contract tests (still) tests that the generated schemas matches the contracts. But now it also tests that all views we create are also in the data product list

test: Improve data product contract test

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj
source/dotnet/Measurements.Client/MeasurementsClient.cs

Measurements API: Use v2/aggregatedByMonth endpoint

---

source/core/src/core/silver/domain/constants/enums/quality_dh2_enum.py
source/core/src/core/silver/domain/transformations/migrations_transformation.py
source/core/tests/helpers/builders/migrated_transactions_builder.py
source/core/tests/unit_tests/silver/domain/transformations/test_migrations_transformation.py

There were no transformations for migrated quality towards measurements gold

fix: Migration quality transformation

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Application/Handlers/IMeasurementsHandler.cs
source/dotnet/Measurements.Application/Responses/MeasurementsAggregatedByDateResponse.cs
source/dotnet/Measurements.Application/Responses/MeasurementsAggregatedByMonthResponse.cs
source/dotnet/Measurements.Application/Responses/MeasurementsResponse.cs
source/dotnet/Measurements.Client/Measurements.Client.csproj
source/dotnet/Measurements.Infrastructure/Handlers/MeasurementsHandler.cs
source/dotnet/Measurements.UnitTests/Application/Responses/GetAggregatedMeasurementsResponseTests.cs
source/dotnet/Measurements.UnitTests/Application/Responses/MeasurementsResponseTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Controllers/MeasurementsControllerTests.cs
source/dotnet/Measurements.WebApi.UnitTests/MeasurementsControllerTests.cs

Response types are renamed as agreed on an earlier PR.
No functional changes.

refac: [MeasurementsApi] Rename response types

---

source/core/tests/integration/features/stream_bronze_to_silver.feature
source/core/tests/integration/features/stream_calculated_measurements_to_gold_measurements.feature
source/core/tests/integration/features/stream_migrated_bronze_measurements_to_gold_measurements.feature
source/core/tests/integration/features/stream_submitted_silver_measurements_to_gold_measurements.feature
source/core/tests/integration/step_definitions/test_stream_bronze_to_silver.py
source/core/tests/integration/step_definitions/test_stream_calculated_measurements_to_gold_measurements.py
source/core/tests/integration/step_definitions/test_stream_migrated_bronze_measurements_to_gold_measurements.py
source/core/tests/integration/step_definitions/test_stream_submitted_silver_measurements_to_gold_measurements.py

test: change "then"

---

source/core/pyproject.toml
source/core/uv.lock

feat: undo protobuf downgrade

---

source/core/pyproject.toml
source/core/uv.lock

fix: Version not aligned 

---

source/dotnet/Measurements.Domain/Year.cs
source/dotnet/Measurements.Infrastructure/Extensions/DateAndTimeExtensions.cs
source/dotnet/Measurements.Infrastructure/Persistence/Queries/GetAggregatedByDateQuery.cs
source/dotnet/Measurements.Infrastructure/Persistence/Queries/GetAggregatedByMonthQuery.cs
source/dotnet/Measurements.UnitTests/Domain/YearTests.cs
source/dotnet/Measurements.UnitTests/Extensions/DateAndTimeExtensionsTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Controllers/MeasurementsControllerTests.cs
source/dotnet/Measurements.WebApi.IntegrationTests/Fixtures/WebApiFixture.cs

https://github.com/energinet-datahub/team-raccoons/issues/1249

fix: [MeasurementsApi] Include last day of month and last day of year

---

.github/actions/dotnet-tests-prepare-outputs/action.yml
.github/workflows/ci-dotnet.yml

Use generic test output folder path

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Api/Models/MeasurementAggregationByDateDto.cs
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client.IntegrationTests/MeasurementClientTests.cs
source/dotnet/Measurements.Client.UnitTests/Assets/MeasurementsAggregatedByDate.json
source/dotnet/Measurements.Client.UnitTests/Assets/MeasurementsAggregatedByDateMissingMeasurements.json
source/dotnet/Measurements.Client.UnitTests/Assets/MeasurementsAggregatedByMonth.json
source/dotnet/Measurements.Client.UnitTests/Assets/MeasurementsAggregatedByYear.json
source/dotnet/Measurements.Client.UnitTests/MeasurementsClientTests.cs
source/dotnet/Measurements.Client/Measurements.Client.csproj
source/dotnet/Measurements.UnitTests/Application/Responses/MeasurementsAggregatedByMonthResponseTests.cs
source/dotnet/Measurements.UnitTests/Application/Responses/MeasurementsAggregatedByYearResponseTests.cs

Fix qualities update in client dto

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Measurements.Client.csproj

Bump meas client

---

source/core/tests/subsystem_tests/builders/calculated_measurements_row_builder.py
source/core/tests/subsystem_tests/fixtures/calculated_measurements_fixture.py

New columns have been added and forgot to add it to the insert which resulted in an error when trying to insert.

fix: Fix calculated subsystem test

---

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md
source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj
source/dotnet/Measurements.Client/Extensions/DependencyInjection/ClientExtensions.cs
source/dotnet/Measurements.Client/Measurements.Client.csproj

Fix bug in MeasurementsClient DI reported by Team Atlas.

Fix missing dependency bug
