source/electrical_heating/contracts/electricity_market__electrical_heating/consumption_metering_point_periods_v1.py, source/electrical_heating/tests/integration_tests/calculation_scenarios/given_a_smoke_test_scenario/when/electricity_market__electrical_heating/consumption_metering_point_periods_v1.csv
We need to know the metering point periods that must be reset.
=> feat: Include periods where EH has previously been registered

.docker/requirements.txt, source/electrical_heating/setup.py, source/electrical_heating/tests/integration_tests/calculation_scenarios/wip_move_consumption_to_child/test_it.py
Due to an error in `opengeh-python-packages` release 2.5.0 did not exist.
=> fix: Fix python package refs

source/capacity_settlement/tests/testsession.local.settings.sample.yml, source/electrical_heating/tests/testsession.local.settings.sample.yml, source/electrical_heating/tests/testsession_configuration.py
Somehow the ignore_extra_columns_in_actual was not added in a former PR.
This is corrected.
=> test: Add ignore_extra_columns_in_actual to sample configuration

.docker/requirements.txt
=> chore: bump virtualenv from 20.24.2 to 20.26.6 in /.docker

source/capacity_settlement/src/contracts/electricity_market__capacity_settlement/metering_point_periods_v1.py, source/capacity_settlement/tests/scenario_tests/given_a_smoke_test_scenario/test_scenario.py, source/capacity_settlement/tests/scenario_tests/given_a_smoke_test_scenario/when/electricity_market__capacity_settlement/metering_point_periods_v1.csv, source/capacity_settlement/tests/scenario_tests/wip_change_to_summertime/when/electricity_market__capacity_settlement/metering_point_periods_v1.csv, source/capacity_settlement/tests/scenario_tests/wip_change_to_wintertime/when/electricity_market__capacity_settlement/metering_point_periods_v1.csv, source/capacity_settlement/tests/scenario_tests/wip_leap_year_calculation_period/when/electricity_market__capacity_settlement/metering_point_periods_v1.csv, source/capacity_settlement/tests/scenario_tests/wip_leap_year_selection_period/when/electricity_market__capacity_settlement/metering_point_periods_v1.csv
According to SME child_period_from_date/child_period_to_date matcher better with the business process than coupled_date /decopled_date
=> refac: Use child_period_from_date and child_period_to_date instead of coupled_date decopled_date

.github/actions/create-prerelease/action.yml
dh3-environments expects released wheel to be inside a `dist` folder in the zipped release. This PR ensures that this happens.
=> ci: released wheel should be within a  folder

.github/actions/promote-prerelease/action.yml
CD workflow fails if '{package}_latest' does not exist - it shouldn't.
=> ci: gh release delete throws when a release does not exist

.github/workflows/ci-orchestrator.yml
Fixes a typo in `ci-orchestrator` that meant no release matrix was ever created resulting in the failure of the `create_release` job.
=> ci: fix typo in if condition

.github/actions/create-prerelease/action.yml
Since we no longer prepackage release artifacts, we have to change where we find `container_tests`.
=> ci: we no longer prepackage releases

docs/gold/table_definitions/gold_measurements.md, docs/silver/table_definitions/silver_measurements.md
Fix: removes `electrical_heating` and `capacity_settlement` from silver's `orchestration_type`
Adds `orchestration_type` to gold and values for `metering_point_type` and `quality`
Minor text changes.
https://github.com/Energinet-DataHub/team-volt/issues/1069
=> Docs: Fix orchestration type in silver def - and add it to gold, plus some

source/geh_calculated_measurements/tests/capacity_settlement/subsystem_tests/test_capacity_settlement.py, source/geh_calculated_measurements/tests/electrical_heating/subsystem_tests/test_electrical_heating.py
=> test: orchestration_instance_id use underscore not dashes

source/geh_calculated_measurements/tests/capacity_settlement/conftest.py, source/geh_calculated_measurements/tests/capacity_settlement/job_tests/conftest.py, source/geh_calculated_measurements/tests/data_products/conftest.py, source/geh_calculated_measurements/tests/electrical_heating/conftest.py, source/geh_calculated_measurements/tests/electrical_heating/job_tests/conftest.py, source/geh_calculated_measurements/tests/missing_measurements_log/conftest.py
Eliminate the unused `tests_path` fixture from multiple `conftest.py` files to streamline the test configuration. This change enhances code clarity and maintainability.
=> Refactor: Remove unused tests_path fixture from conftest.py files

source/geh_calculated_measurements/src/geh_calculated_measurements/net_consumption_group_6/domain/cenc.py
The dummy data = [("orchestration_instance_id", "metering_point_id", 1.0, 2021, 1)]
was changed to  data = [.("orchestration_instance_id", "metering_point_id", 1.000, 2021, 1)].
=> fix: Subsystem test  - corrected number of decimals

.github/workflows/cd.yml, .github/workflows/detect-changes.yml
When there was made changes in both python and dotnet, then only dotnet was deployed. We would like both to be deployed.
=> fix: Deploy both databricks when changes are made

source/geh_calculated_measurements/tests/subsystem_tests/net_consumption_group_6/test_jobs.py
Activate the test for writing data to delta, which was previously skipped due to incomplete implementation.
The change is tested on dev_002 [here](https://github.com/Energinet-DataHub/dh3-environments/actions/runs/14055271262/job/39353383785). This is extracted from the test output:
`tests/subsystem_tests/net_consumption_group_6/test_jobs.py::TestNetConsumptionGroup6::test__and_then_data_is_written_to_delta <- tests/subsystem_tests/base_resources/base_job_tests.py PASSED`
The subsystem tests, however, failed. But that was for other reasons that I anticipate to be period as they should not be related to this change.
=> Enable test for writing output in net consumption group 6

.github/workflows/ci-orchestrator.yml, source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/entry_point.py, source/geh_calculated_measurements/src/geh_calculated_measurements/database_migrations/migrations_runner.py, source/geh_calculated_measurements/src/geh_calculated_measurements/testing/utilities/create_azure_log_query_runner.py, source/geh_calculated_measurements/src/geh_calculated_measurements/testing/utilities/log_query_client_wrapper.py, source/geh_calculated_measurements/tests/__init__.py, source/geh_calculated_measurements/tests/capacity_settlement/capacity_settlement_tests/application/job_args/test_capacity_settlement_job_args.py, source/geh_calculated_measurements/tests/capacity_settlement/job_tests/__init__.py, source/geh_calculated_measurements/tests/capacity_settlement/job_tests/test_capacity_settlement_job.py, source/geh_calculated_measurements/tests/conftest.py, source/geh_calculated_measurements/tests/data_products/conftest.py, source/geh_calculated_measurements/tests/data_products/contract_and_database_are_equal/test_contract_and_database_equality.py, source/geh_calculated_measurements/tests/data_products/given_calculated_measurements/test_scenario.py, source/geh_calculated_measurements/tests/electrical_heating/electrical_heating_tests/application/test_electrical_heating_job_args.py, source/geh_calculated_measurements/tests/electrical_heating/job_tests/test_electrical_heating_job.py, source/geh_calculated_measurements/tests/integration/database_migrations/test_migrate.py, source/geh_calculated_measurements/tests/missing_measurements_log/missing_measurements_log_tests/application/test_missing_measurements_log_job_args.py, source/geh_calculated_measurements/tests/net_consumption_group_6/job_tests/__init__.py, source/geh_calculated_measurements/tests/net_consumption_group_6/job_tests/test_net_consumption_group_6_job.py
- Made a new folder called `integration` for tests that require the integration test environment
- Removed session-scoped `dummy_logging` - this must now be used explicitly.
- Removed a various unnecessary fixtures around the code base
- Changed `scenario_parameters.yml` values to follow contracts
Sub task of https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/586
=> chore: add logging to migration start

source/core/src/core/silver/infrastructure/repositories/silver_measurements_repository.py, source/core/src/core/silver/infrastructure/repositories/submitted_transactions_repository.py, source/core/tests/silver/infrastructure/repositories/test_submitted_transactions_repository.py
As we have made changes to our data the stream readings from silver are failing. This is because it does not expect changes to be made. 
When adding `skipChangeCommit` it will ignore those changes.
=> chore: Set `skipChangeCommit` when reading from silver

source/geh_calculated_measurements/tests/net_consumption_group_6/scenario_tests/nsg6_up_to_end_change_to_summer_time/then/measurements.csv, source/geh_calculated_measurements/tests/net_consumption_group_6/scenario_tests/nsg6_up_to_end_simple_scenario_cenk_d15/then/measurements.csv, source/geh_calculated_measurements/tests/net_consumption_group_6/scenario_tests/nsg6_up_to_end_simple_scenario_cenk_d15_multiple_days/then/measurements.csv
Update measurement files to replace the term "Cenk" with "CENC" for consistency and accuracy in calculated estimated netto consumption descriptions.
=> Use correct term "CENC" in measurement files

source/geh_calculated_measurements/src/geh_calculated_measurements/common/domain/model/current_measurements.py, source/geh_calculated_measurements/src/geh_calculated_measurements/common/infrastructure/current_measurements/repository.py, source/geh_calculated_measurements/tests/common/infrastructure/current_measurements/test_repository.py
Update CurrentMeasurements to utilize the schema from measurements_gold, enhancing data reading in the repository. Adjust tests to ensure compliance with the new schema.
Fixes and improvements:
- Test of bad input schema improved to ensure helpful error message (test__when_invalid_contract_raises_with_useful_message)
- Fixed usage of the wrong duplicate of the contract by replacing it with current_v1 from geh_common
- Ensure that the tests do not potentially break other tests (by stopping modifying shared state - i.e., the delta tables)
- Ensure that the fixture `valid_df` that _claims_ to create valid data frame actually does it
- Make catalog_name ctor arg of repository mandatory as it should always be provided
=> Refactor CurrentMeasurements to use measurements_gold schema

source/core/src/core/silver/infrastructure/config/spark_session.py
Corrected a typo in the Spark configuration setting for shuffle partitions.
=> Fix typo in spark_session.py configuration

docs/Measurements.Client/ReleaseNotes/ReleaseNotes.md, source/dotnet/Measurements.Abstractions/Api/Models/AggregatedMeasurements.cs, source/dotnet/Measurements.Abstractions/Measurements.Abstractions.csproj, source/dotnet/Measurements.Application/Persistence/AggregatedMeasurementsResult.cs, source/dotnet/Measurements.Application/Responses/GetAggregatedMeasurementsResponse.cs, source/dotnet/Measurements.Client/Measurements.Client.csproj, source/dotnet/Measurements.Domain/MeasurementAggregation.cs, source/dotnet/Measurements.Infrastructure/Persistence/Queries/AggregatedMeasurementsConstants.cs, source/dotnet/Measurements.Infrastructure/Persistence/Queries/GetAggregatedMeasurementsQuery.cs, source/dotnet/Measurements.UnitTests/Application/Responses/GetAggregatedMeasurementsResponseTests.cs, source/dotnet/Measurements.UnitTests/Infrastructure/Persistence/Queries/GetAggregatedMeasurementsQueryTests.cs
The UI needs an indication of whether an aggregation contains updated values of single observations:
http://github.com/Energinet-DataHub/team-volt/issues/1109
=> [MeasurementsApi] ContainsUpdatedValues added to MeasurementAggregationDto

source/geh_calculated_measurements/tests/subsystem_tests/missing_measurements_log/seed_table.py, source/geh_calculated_measurements/tests/subsystem_tests/net_consumption_group_6/seed_table.py
Disable certain test statements that cannot be executed due to data modification restrictions through views. This change prevents broken tests from affecting the test suite.
=> hack: Disable broken subsystem tests

source/geh_calculated_measurements/src/geh_calculated_measurements/missing_measurements_log/infrastructure/missing_measurements_log_repository.py
This PR is only made to activate deployment on preprod.
Due to an error, the alle electrical heating wheels on preprod have been deleted.
=> test: Activate calculated measurements deployment 

source/dotnet/Measurements.WebApi/Controllers/MeasurementsController.cs
An old version of MeasurementsClient using a two majors old version of MeasurementsApi is still in use in BFF:
This PR temporarily reintroduces v2, until BFF is using the latest version of MeasurementsClient (v.8.0.0)
=> [MeasurementsApi] Temporarily reintroduce v2

source/geh_calculated_measurements/src/geh_calculated_measurements/missing_measurements_log/domain/calculation.py
We want to avoid doing transformations on the entire current_v1 data when we only want a limit time period.
=> refac: Filter current_v1 by period in missing measurements log

source/dotnet/Measurements.WebApi/Assets/PerformanceTests/Aggregated/ByPeriod/aggregatedByPeriodWithDailyAggregates.yaml, source/dotnet/Measurements.WebApi/Assets/PerformanceTests/Aggregated/ByPeriod/aggregatedByPeriodWithHourlyAggregates.yaml, source/dotnet/Measurements.WebApi/Assets/PerformanceTests/Aggregated/ByPeriod/aggregatedByPeriodWithMonthlyAggregates.yaml, source/dotnet/Measurements.WebApi/Assets/PerformanceTests/Aggregated/ByPeriod/aggregatedByPeriodWithQuarterlyAggregates.yaml, source/dotnet/Measurements.WebApi/Assets/PerformanceTests/Aggregated/ByPeriod/aggregatedByPeriodWithYearlyAggregates.yaml
We've seen consistently low median response times as a result of the last week of running the MeasurementsApi performance tests:
https://github.com/Energinet-DataHub/dh3-environments/actions/workflows/measurements-tests-scheduled.yml
To get notified if/when anything degrades the performance we decrease the valid median response times to 800ms.
=> tests: Decrease valid median of response times
